name: filtro por paises

on:
  schedule:
    - cron: '00 0 * * *' # Runs every day at 00:00 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  analizando_datos:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: crear tablas por pais
        run: |
          grep -i Germany companies-all.csv  > companies_germany.csv
          grep -i Kingdom companies-all.csv  > companies_united_kingdom.csv
          grep -i France companies-all.csv  > companies_france.csv

      - name: Commit results
        if: always()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --quiet || git stash
          git pull --rebase origin main
          git stash list | grep "stash@{0}" && git stash apply
          git add .
          git diff --cached --exit-code || git commit -m "tabla actualizada" --allow-empty
          git push --force-with-lease origin HEAD:main
 
  viendo_datos: # nombre del job
    needs: analizando_datos # job(s) de los que depende
    runs-on: macos-12 # sistema operativo
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: imprimir tabla bruta y neta
        run: |
          echo "tabla desde Empreses Francesas"
          cat companies_france.csv
          echo
          echo "tabla desde Empreses Germanas"
          cat companies_germany.csv
          echo
          echo "tabla desde Empreses Inglesas"
          cat companies_united_kingdom.csv
